services:
  ceng-database:
    image: postgres:18.1-alpine
    restart: unless-stopped
    ports:
      - 54322:5432
    volumes:
      - ./volumes/ceng-database:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-casari-eat-n-go}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      POSTGRES_DB: ${POSTGRES_DB:-casari-eat-n-go}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-casari-eat-n-go}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend-network

  ceng-webapp:
    image: lcastelli88/backend-webapp:latest
    restart: unless-stopped
    ports:
      - 8001:8001
    depends_on:
      ceng-database:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-ceng-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-casari-eat-n-go}
      DB_PASSWORD: ${DB_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      DB_NAME: ${DB_NAME:-casari-eat-n-go}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
      DB_LOG_SLOW_QUERY_THRESHOLD: ${DB_LOG_SLOW_QUERY_THRESHOLD:-1}
      APP_PORT: ${APP_PORT:-8001}
      APP_MODE: ${APP_MODE:-debug}
      APP_CORS_ORIGIN: ${APP_CORS_ORIGIN:-*}
      SEARCH_RELEVANCE_THRESHOLD: ${SEARCH_RELEVANCE_THRESHOLD:-0.05}
      PUBSUB_PERSIST_EVENTS_ON_DB: ${PUBSUB_PERSIST_EVENTS_ON_DB:-true}
      PUBSUB_PERSIST_EVENTS_RETENTION_DAYS: ${PUBSUB_PERSIST_EVENTS_RETENTION_DAYS:-365}
      PUBSUB_SYNC_MODE: ${PUBSUB_SYNC_MODE:-false}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET:-ef1522b2795ee160c75900c181bd64cdc11160ef148b6bb906a4d44b900f68b4}
      AUTH_JWT_ACCESS_TOKEN_DURATION: ${AUTH_JWT_ACCESS_TOKEN_DURATION:-600}
      AUTH_JWT_REFRESH_TOKEN_DURATION: ${AUTH_JWT_REFRESH_TOKEN_DURATION:-86400}
    healthcheck:
      test: >
        sh -c 'wget -S -q  -O -  http://127.0.0.1:8001/api/v1/health-check 2>&1 >/dev/null | grep "200 OK"'
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend-network

  ceng-migrate:
    image: lcastelli88/backend-migrate:latest
    restart: no
    depends_on:
      ceng-database:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-ceng-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-casari-eat-n-go}
      DB_PASSWORD: ${DB_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      DB_NAME: ${DB_NAME:-casari-eat-n-go}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
    networks:
      - backend-network

  ceng-cli:
    image: lcastelli88/backend-cli:latest
    restart: no
    depends_on:
      ceng-webapp:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-ceng-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-casari-eat-n-go}
      DB_PASSWORD: ${DB_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      DB_NAME: ${DB_NAME:-casari-eat-n-go}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
      DB_LOG_SLOW_QUERY_THRESHOLD: ${DB_LOG_SLOW_QUERY_THRESHOLD:-1}
      APP_PORT: ${APP_PORT:-8001}
      APP_MODE: ${APP_MODE:-debug}
      APP_CORS_ORIGIN: ${APP_CORS_ORIGIN:-*}
      SEARCH_RELEVANCE_THRESHOLD: ${SEARCH_RELEVANCE_THRESHOLD:-0.05}
      PUBSUB_PERSIST_EVENTS_ON_DB: ${PUBSUB_PERSIST_EVENTS_ON_DB:-true}
      PUBSUB_PERSIST_EVENTS_RETENTION_DAYS: ${PUBSUB_PERSIST_EVENTS_RETENTION_DAYS:-365}
      PUBSUB_SYNC_MODE: ${PUBSUB_SYNC_MODE:-false}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET:-ef1522b2795ee160c75900c181bd64cdc11160ef148b6bb906a4d44b900f68b4}
      AUTH_JWT_ACCESS_TOKEN_DURATION: ${AUTH_JWT_ACCESS_TOKEN_DURATION:-600}
      AUTH_JWT_REFRESH_TOKEN_DURATION: ${AUTH_JWT_REFRESH_TOKEN_DURATION:-86400}
    networks:
      - backend-network

  ceng-frontend:
    image: lcastelli88/frontend-webapp:latest
    restart: unless-stopped
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://192.168.178.100:8001}
    healthcheck:
      test: ["CMD", "nginx", "-v"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
